import { useState } from 'react';
import { sdk } from '@/services/sdk';
import { useFetch } from '@/hooks/useFetch';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
const PRODUCT_FIELDS=['Name','mrp_c','purchase_rate_c','purchase_unit_c','image_c','favourite_c','sort_position_c','CreatedOn'];
export const route={path:'/settings',layout:'owner',access:'public'};
export const nav={label:'Backup',icon:'Archive'};
export default function Settings(){
 const {data}=useFetch(()=>sdk.table('products_c').select(PRODUCT_FIELDS).orderBy('sort_position_c').limit(500,0).fetch().then(r=>{if(!r.success)throw new Error(r.message);return r.data;}),[]);
 const products=data??[];const [importing,setImporting]=useState(false);const [pending,setPending]=useState(null);
 function exportProducts(){const backup={app:'Balaji Namkeen',backupType:'products',version:2,exportedAt:new Date().toISOString(),fields:['Id','Name','mrp_c','purchase_rate_c','purchase_unit_c','image_c','favourite_c','sort_position_c','CreatedOn'],products};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='Balaji_Namkeen_Products_Backup.json';link.click();URL.revokeObjectURL(url);toast.success(products.length+' products exported with all fields and images.');}
 async function readBackup(event){const file=event.target.files?.[0];if(!file)return;try{const backup=JSON.parse(await file.text());if(backup?.app!=='Balaji Namkeen'||backup?.backupType!=='products'||!Array.isArray(backup.products))throw new Error('Invalid Balaji Namkeen product backup.');setPending({backup,input:event.target});}catch(e){toast.error(e.message||'Could not read backup.');event.target.value='';}}
 async function confirmImport(){if(!pending)return;setImporting(true);try{let restored=0;for(const product of pending.backup.products){if(!product?.Name)continue;const existing=product.Id?await sdk.table('products_c').select(PRODUCT_FIELDS).get(product.Id):{data:null};const payload={Name:String(product.Name),mrp_c:Number(product.mrp_c||0),purchase_rate_c:Number(product.purchase_rate_c||0),purchase_unit_c:product.purchase_unit_c||'Patti',image_c:product.image_c||'',favourite_c:Boolean(product.favourite_c),sort_position_c:Number(product.sort_position_c||Date.now())};const result=existing?.data?await sdk.table('products_c').update({Id:product.Id,...payload}):await sdk.table('products_c').create(payload);if(result.data?.length)restored++;}toast.success(restored+' products imported with all available fields.');}catch(e){toast.error(e.message||'Could not import backup.');}finally{setImporting(false);pending.input.value='';setPending(null);}}
 return <div className="mx-auto max-w-2xl space-y-5"><div><h1 className="text-3xl font-bold">Backup & Restore</h1><p className="text-sm text-muted-foreground">Product catalogue only: every product field, pricing, unit, favourite, sort position and image.</p></div><section className="space-y-4 rounded-xl border border-border bg-card p-4"><div className="font-semibold">Export Products</div><div className="text-sm text-muted-foreground">{products.length} products ready. Images are included in the backup data.</div><Button onClick={exportProducts} disabled={!products.length}>Export Products</Button></section><section className="space-y-4 rounded-xl border border-border bg-card p-4"><div className="font-semibold">Import Products</div><div className="text-sm text-muted-foreground">Restore names, images, pricing, units, favourites and sorting.</div><label className="inline-flex cursor-pointer rounded-md border border-border px-4 py-2 text-sm font-semibold hover:bg-accent">{importing?'Importing…':'Choose Backup File'}<input type="file" accept=".json,application/json" onChange={readBackup} className="hidden" disabled={importing}/></label>{pending&&<div className="rounded-xl border border-warning/30 bg-warning/10 p-4"><div className="font-semibold">Restore this backup?</div><p className="mt-1 text-sm text-muted-foreground">{pending.backup.products.length} products are ready to import. Existing products with the same ID will be updated.</p><div className="mt-3 flex gap-2"><Button onClick={confirmImport} disabled={importing}>{importing?'Importing…':'Confirm Import'}</Button><Button variant="outline" onClick={()=>{pending.input.value='';setPending(null)}} disabled={importing}>Cancel</Button></div></div>}</section></div>;
}
